version: '3'

services:
  teste-postgres-compose:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "15432:5432"
    volumes:
      - C:/Desenvolvimento/workspace_kid/storagepostgres:/var/lib/postgresql/data

      
